name: TSK Release Build

on:
  workflow_dispatch: # Manual trigger
      inputs:
        ref:
          description: "Branch or tag"
          type: string
          required: true
          default: "sleuthkit-4.15.0"
  push:

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: ${{ matrix.os }}-${{ matrix.arch }}
    runs-on: ${{ matrix.runner }}
    outputs:
      commit: ${{ steps.checkout_tsk.outputs.commit }}
    strategy:
      fail-fast: false
      matrix:
        include:
          # --- Linux ---
          - os: linux
            arch: x86_64
            runner: ubuntu-latest
          - os: linux
            arch: aarch64
            runner: ubuntu-24.04-arm # Native GitHub ARM runner

          # --- macOS ---
          - os: macos
            arch: x86_64
            runner: macos-26-intel
          - os: macos
            arch: aarch64
            runner: macos-26 # Apple Silicon

          # --- Windows ---
          - os: windows
            arch: x86_64
            runner: windows-2025
            vs_arch: x64
          - os: windows
            arch: aarch64
            runner: windows-11-arm
            vs_arch: ARM64

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Checkout Code
        uses: actions/checkout@v6
        id: checkout_tsk
        with:
          path: "${{ github.workspace }}/tsk"
          repository: sleuthkit/sleuthkit
          ref: ${{ inputs.ref }}
          submodules: recursive

      # - name: Apply MSBuild fix patch
      #   working-directory: "${{ github.workspace }}/tsk"           # Sets the base directory for this step
      #   run: |
      #     git apply ../tsk/patch/fix_msbuild.patch

      # --- Dependency Installation ---
      - name: Install Linux Dependencies
        if: matrix.os == 'linux'
        run: |
          sudo apt update
          sudo apt install -y tree ant autoconf automake g++ libssl-dev afflib-tools libewf-dev libqcow-dev libvhdi-dev libvmdk-dev libmagic-dev libtool make pkg-config zlib1g-dev wget

      - name: Install macOS Dependencies
        if: matrix.os == 'macos'
        run: |
          brew install automake autoconf libtool libewf libmagic sqlite tree

      - name: Install Chocolatey
        if: matrix.os == 'windows'
        run: |
          Set-ExecutionPolicy Bypass -Scope Process -Force;
          [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072;
          iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
          choco install nuget.commandline
          choco install ant --ignore-dependencies

      - name: tree
        if: matrix.os == 'windows'
        run: |
          tree /F
      - name: tree
        if: matrix.os == 'linux'
        run: |
          tree
      - name: tree
        if: matrix.os == 'macos'
        run: |
          tree

  #     - name: Set up JDK 17
  #       if: matrix.os == 'windows'
  #       uses: actions/setup-java@v4
  #       with:
  #         distribution: 'zulu' # choose 'temurin', 'zulu' or 'adopt'
  #         java-version: '17'

  #     - name: Set JDK_HOME and INCLUDE
  #       if: matrix.os == 'windows'
  #       shell: bash
  #       run: |
  #         echo "JDK_HOME=$JAVA_HOME" >> $GITHUB_ENV
  #         echo "INCLUDE=$INCLUDE;$JAVA_HOME/include;$JAVA_HOME/include/win32" >> $GITHUB_ENV

  #     # --- Build POSIX (Linux/macOS) ---
  #     - name: Build POSIX
  #       if: matrix.os != 'windows'
  #       working-directory: "${{ github.workspace }}/tsk"
  #       run: |
  #         mkdir install_dir
  #         ./bootstrap
  #         ./configure --disable-java --prefix=$(pwd)/install_dir
  #         make -j$(nproc 2>/dev/null || sysctl -n hw.ncpu)
  #         make install

  #     # --- Build Windows ---
  #     - name: Build Windows
  #       if: matrix.os == 'windows'
  #       working-directory: "${{ github.workspace }}/tsk"
  #       shell: pwsh
  #       env:
  #         TSK_HOME: "${{ github.workspace }}/tsk"
  #       run: |
  #         # Use TSK's provided build script
  #         # Note: We pass the architecture to MSBuild via the python wrapper if supported, 
  #         # otherwise, we trigger MSBuild directly.
  #         python win32/updateAndBuildAll.py
          
  #         mkdir install_dir/x32
  #         cp -ErrorAction Ignore -r win32/Release install_dir/x32/ 
  #         cp -ErrorAction Ignore -r win32/Release_NoLibs install_dir/x32/
  #         cp -ErrorAction Ignore -r win32/x64 install_dir/

  #     # --- Handle Manual Workflow Dispatch (Artifacts only) ---
  #     - name: Upload Artifacts
  #       uses: actions/upload-artifact@v7
  #       with:
  #         name: tsk-${{ matrix.os }}-${{ matrix.arch }}
  #         path: "${{ github.workspace }}/tsk/install_dir"
  #         overwrite: true
  #         archive: true

  # release:
  #   if: always() && !cancelled()
  #   needs: build
  #   runs-on: ubuntu-latest
  #   timeout-minutes: 10
  #   permissions:
  #     contents: write
  #     packages: write
  #     actions: write
  #     id-token: write
  #     attestations: write
    
  #   steps:
  #     - uses: actions/download-artifact@v8
  #       with:
  #         pattern: tsk-*
  #         path: release
  #         merge-multiple: true
  #         skip-decompress: true

  #     - name: Prep Release Notes
  #       working-directory: release
  #       run: |
  #         echo 'source: sleuthkit/sleuthkit@${{ needs.build.outputs.commit }}' | tee ../notes.md
  #         echo -e '\n```sh\necho $hash $filename | sha1sum -c\n' | tee -a ../notes.md
  #         sha1sum $(ls) | tee -a ../notes.md
  #         echo '```' | tee -a ../notes.md

  #     - name: Generate Provenance Attestation
  #       uses: actions/attest@v4
  #       with:
  #         subject-path: "release/*"

  #     - name: Release
  #       uses: ncipollo/release-action@v1
  #       with:
  #         tag: tsk/${{ needs.build.outputs.commit }}
  #         name: tsk@${{ inputs.ref }}
  #         makeLatest: true
  #         prerelease: false
  #         allowUpdates: false
  #         replacesArtifacts: false
  #         draft: true
  #         immutableCreate: true
  #         updateOnlyUnreleased: true
  #         skipIfReleaseExists: true
  #         artifacts: "release/*"
  #         bodyFile: "notes.md"
  #         token: ${{ github.token }} 